### DISCUSSION TITLE
`x env ls -i`命令查看隐式安装的库

### DISCUSSION THREAD

**Discussion by MaxforCherubim** [x-cmd/x-cmd#126] [Q&A] [answered]
1. 安装starship
```
% x starship
- I|starship: Download starship.preview.tar.xz
  more:
    url: https://oss.resource.x-cmd.com/x-cmd/theme/dist/starship.preview.tar.xz
- I|pkg: Trying download ==> 'fzf v0.55.0'
- I|pkg: |
    download fzf=v0.55.0, thanks to the courtesy of https://registry.npmmirror.com
  more:
    url: https://registry.npmmirror.com/@x-cmd-pkg/fzf/-/fzf-0.0.0-v0.55.0-darwin.arm64.0.tgz
    ball: /Users/zhangyingtan/.x-cmd.root/local/data/pkg/download/fzf/v0.55.0.darwin.arm64.0.tgz
    name: fzf
    version: v0.55.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   265    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
######################################################################## 100.0%##O#-#     ######################################################################## 100.0%
- I|pkg: Trying populate ==> 'fzf v0.55.0'
- I|pkg: Unpacking
  more:
    ball: /Users/zhangyingtan/.x-cmd.root/local/data/pkg/download/fzf/v0.55.0.darwin.arm64.0.tar.xz
    target_dir: /Users/zhangyingtan/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/fzf/v0.55.0
- I|pkg: Unpacking completed
- I|pkg: Running /Users/zhangyingtan/.x-cmd.root/local/data/pkg/metadata/v0.1.1/pkg/data/fzf/.x-cmd/populate.sh
- I|x_cmd_pkg: shim gen
  more:
    source: /Users/zhangyingtan/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/fzf/v0.55.0/bin/
    shim_bin: /Users/zhangyingtan/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/fzf/v0.55.0/shim_bin/
    adaptive_shim_bin: /Users/zhangyingtan/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/fzf/v0.55.0/adaptive_shim_bin/
- I|pkg: fzf v0.55.0 install successfully
```
2. 发现给我安装了fzf后，查看env
```
% x env ls
- E|pick: |
    The data is empty
```
- 我mac最近重制了，想要配置更加精简的mac，所以一切都是空白的。
- 我能理解为了以交互式的形式显示`x starship`的结果，要给我自动安装fzf，不过为什么在env里找不到？
