### ISSUE TITLE
[BUG] Error Encountered with x ohmypush Command Due to Missing themes.zip.sha256 File

### ISSUE THREAD

**Issue by Xu-Lan** [x-cmd/x-cmd#203]
### 💬 Describe the bug

When running x ohmypush use catppuccin_mocha, the themes.zip.sha256 file is no longer provided by ohmypush, preventing SHA256 verification of themes.zip, This compromises file integrity checks.

![Image](https://github.com/user-attachments/assets/e3462a67-f9e1-4f9d-be86-ac410e2143b2)

### 📄 System

```yaml
- Version: [b4cc02f12a5f72faa5290792dff41b4a3fef163438d17bd184c78ed8a75660579ca314caf5695dcbfa58fbfe17d8c736229504a4ddbebeb05168a866cbe3bff2]
- Shell: [Bash]
- OS: [Linux]
- Arch: [amd64]
```

### 🔎 To Reproduce

1. Run the command `x ohmypush use catppuccin_mocha`.
2. Observe the error messages related to the download and SHA256 verification failure.
