### ISSUE TITLE
[BUG] `x emoji` gets black screen | [mod=emoji]

### ISSUE THREAD

**Issue by edwinjhlee** [x-cmd/x-cmd#238]
### 💬 Describe the bug

1. `x emoji`
2. Then get black screen

### 📄 System

```yaml
- name: x-cmd
  info: |-
    ___X_CMD_VERSION:           x0
    ___X_CMD_PKG_VERSION:       v0.1.2
    ___X_CMD_WEBSRC_REGION:     cn
    ___X_CMD_LANG:              zh
    x-cmd sum:                  ed2bbf968c97e1eab9a526ae32d22ad4768a8421c97a5cf77ed13dbc8a32c000f7d80904b473b58e9d0575ba9ef4f8ab7bdaaeb84020d67781e56614668c6c9f
    
    ==== root ls ====
    V:          <<HOME-STRING>>/.x-cmd.root/v
    ROOT:       <<HOME-STRING>>/.x-cmd.root
    CODE:       <<HOME-STRING>>/.x-cmd.root/v/x0
    ADV:        <<HOME-STRING>>/.x-cmd.root/v/x0/adv
    MOD:        <<HOME-STRING>>/.x-cmd.root/v/x0/mod
    METADATA:   <<HOME-STRING>>/.x-cmd.root/v/x0/.x-cmd/metadata
    GDATA:      <<HOME-STRING>>/.x-cmd.root/global/data
    DATA:       <<HOME-STRING>>/.x-cmd.root/local/data
    USR:        <<HOME-STRING>>/.x-cmd.root/local/usr
    ART:        <<HOME-STRING>>/.x-cmd.root/local/art
    GCFG:       <<HOME-STRING>>/.x-cmd.root/global/cfg
    CFG:        <<HOME-STRING>>/.x-cmd.root/local/cfg
    LOG:        <<HOME-STRING>>/.x-cmd.root/local/log
    CACHE:      <<HOME-STRING>>/.x-cmd.root/local/cache
    TMP:        <<HOME-STRING>>/.x-cmd.root/local/tmp
    SHARED:     <<HOME-STRING>>/.x-cmd.root/global/shared
    
    ==== boot rc ====
    export ASDF_DIR='<<HOME-STRING>>/.x-cmd.root/local/data/asdf' ; export ASDF_DATA_DIR='<<HOME-STRING>>/.x-cmd.root/local/data/asdf'; [ ! -f '<<HOME-STRING>>/.x-cmd.root/local/data/asdf/asdf.sh' ] || . '<<HOME-STRING>>/.x-cmd.root/local/data/asdf/asdf.sh' # auto generated: asdf-activate
- name: shell
  info: zsh
- name: awk
  info: awk version 20200816
- name: sed
  info: |-
    /usr/bin/sed: illegal option -- -
    usage: sed script [-EHalnru] [-i extension] [file ...]
    	sed [-EHalnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
- name: grep
  info: grep (BSD grep, GNU compatible) 2.6.0-FreeBSD
- name: find
  info: |-
    /usr/bin/find: illegal option -- -
    usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
           find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
- name: busybox
  info: 
- name: curl
  info: |-
    curl 8.5.0 (aarch64-apple-darwin) libcurl/8.5.0 quictls/3.1.4 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.58.0 ngtcp2/1.1.0 nghttp3/1.1.0
    Release-Date: 2023-12-06
    Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s scp sftp smb smbs smtp smtps telnet tftp ws wss
    Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd
- name: wget
  info: |-
    GNU Wget 1.24.5 在 darwin23.2.0 上编译。
    
    -cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls 
    +ntlm +opie -psl +ssl/openssl 
    
    Wgetrc: 
        /opt/homebrew/etc/wgetrc (系统)
    语区: 
        /opt/homebrew/Cellar/wget/1.24.5/share/locale 
    编译: 
        clang -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/opt/homebrew/etc/wgetrc" 
        -DLOCALEDIR="/opt/homebrew/Cellar/wget/1.24.5/share/locale" -I. 
        -I../lib -I../lib -I/opt/homebrew/opt/openssl@3/include 
        -I/opt/homebrew/Cellar/libidn2/2.3.7/include -DNDEBUG -g -O2 
    链接: 
        clang -I/opt/homebrew/Cellar/libidn2/2.3.7/include -DNDEBUG -g -O2 
        -L/opt/homebrew/Cellar/libidn2/2.3.7/lib -lidn2 
        -L/opt/homebrew/opt/openssl@3/lib -lssl -lcrypto -ldl -lz 
        ../lib/libgnu.a -liconv -lintl -Wl,-framework -Wl,CoreFoundation 
        -Wl,-framework -Wl,CoreServices -lunistring 
    
    Copyright © 2015 Free Software Foundation, Inc.
    授权 GPLv3+: GNU GPL 第三版或更高版本
    <http://www.gnu.org/licenses/gpl.html>。
    这是自由软件：您可以自由地更改并重新分发它。
    在法律所允许的范围内，没有任何担保。
    
    最初由 Hrvoje Nikšić <hniksic@xemacs.org> 编写。
    请将错误报告或建议寄给 <bug-wget@gnu.org>。
- name: release
  info: |-
    Darwin
    24.4.0
```

### 🔎 To Reproduce

1. `x emoji`
2. Then get black screen
