### ISSUE TITLE
["BUG"] Crash trying to install shtris | [pkg=shtris]

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#36]
**Describe the bug**

```
> x env use shtris
- I|pkg: pkg[shtris] version[v3.0.0]  ==>  use 
  S:
  - I|pkg: Step 1/2, Installing shtris v3.0.0
  - I|pkg: Trying download ==> 'shtris v3.0.0'
  - I|pkg: File already downloaded => /Users/ian/.x-cmd.root/local/data/pkg/download/shtris/v3.0.0.darwin.arm64.0.tar.gz
  - I|pkg: Trying populate ==> 'shtris v3.0.0'
  - I|pkg: Unpacking
    more:
      ball: /Users/ian/.x-cmd.root/local/data/pkg/download/shtris/v3.0.0.darwin.arm64.0.tar.gz
      target_dir: /Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0
  - I|pkg: Unpack is done
  - I|pkg: Running /Users/ian/.x-cmd.root/local/data/pkg/metadata/v0.1.1/pkg/common/shtris/.x-cmd/populate.sh
  - I|x_cmd_pkg: shim gen
    more:
      source: /Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0/bin/
      shim_bin: /Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0/shim_bin/
      adaptive_shim_bin: /Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0/adaptive_shim_bin/
  - E|x_cmd_pkg: Not found: [/Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0/bin/shtris]
  - E|pkg: Source /Users/ian/.x-cmd.root/local/data/pkg/metadata/v0.1.1/pkg/common/shtris/.x-cmd/populate.sh failed
  - E|pkg: Failed to add darwin/arm64 'shtris v3.0.0'
  - E|pkg: Cannot install package - 'shtris v3.0.0'
```

**System (please complete the following information):**
 - Version: 6446d9f392c9fe23ec9a7e6e3c68cb5cba16a44ba914609fdd818ead2ccb6b2ec9c6c35dc91b18f488fb78c3528afbe9d7ccce2de355095df062b7d50f93eb0f
 - Shell: Elvish
 - OS: Darwin
 - Arch: arm64

**Comment by edwinjhlee** [comment]
Thank you. This is definitly a bug.

Before we fix this bug, you could try `x shtris` and see whether it works.

**Comment by iandol** [comment]
```
ε ➪ x shtris
- I|pkg: Trying download ==> 'shtris v3.0.0'
- I|pkg: File already downloaded => /Users/ian/.x-cmd.root/local/data/pkg/download/shtris/v3.0.0.darwin.arm64.0.tar.gz
- I|pkg: Trying populate ==> 'shtris v3.0.0'
- I|pkg: Unpacking
  more:
    ball: /Users/ian/.x-cmd.root/local/data/pkg/download/shtris/v3.0.0.darwin.arm64.0.tar.gz
    target_dir: /Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0
- I|pkg: Unpack is done
- I|pkg: Running /Users/ian/.x-cmd.root/local/data/pkg/metadata/v0.1.1/pkg/common/shtris/.x-cmd/populate.sh
- I|x_cmd_pkg: shim gen
  more:
    source: /Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0/bin/
    shim_bin: /Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0/shim_bin/
    adaptive_shim_bin: /Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0/adaptive_shim_bin/
- E|x_cmd_pkg: Not found: [/Users/ian/.x-cmd.root/local/data/pkg/sphere/X/tree.darwin.arm64.0/shtris/v3.0.0/bin/shtris]
- E|pkg: Source /Users/ian/.x-cmd.root/local/data/pkg/metadata/v0.1.1/pkg/common/shtris/.x-cmd/populate.sh failed
- E|pkg: Failed to add darwin/arm64 'shtris v3.0.0'
- E|x: ___x_cmd_which_one fail [code=0]
```
