### ISSUE TITLE
["BUG"] x elv --setup breaks my softlink for rc.elv

### ISSUE THREAD

**Issue by iandol** [x-cmd/x-cmd#56]
**Describe the bug**

I use github to store my dotfiles, including `rc.elv`. I then symlink `rc.elv` to `~/.config/elvish` so it stays up-to-date as I change my files across many machines. You have changed behaviour and now you move `~/.config/elvish/rc.elv` to a backup then write a new rc.elv -- but this now breaks the symlink so my versioned `rc.elv` is not used anymore by elv.

Perhaps you can separate wring new `x.elv` and `a.elv` and injection into `rc.elv`, like a `x elv --setup-modules`. I don't want to inject into rc.elv at all, as I have my rc.elv configured already.

```
ζ ➪ x elv --setup
- I|elv: Adding [files=x.elv,a.elv] to [folder=/Users/ian/.config/elvish/lib]
- I|x: Generating a backup file for /Users/ian/.config/elvish/rc.elv
  more:
    backup: /Users/ian/.config/elvish/rc.elv.bak
- I|x: If you need to restore the original rcfile
  more:
    cmd: mv /Users/ian/.config/elvish/rc.elv.bak /Users/ian/.config/elvish/rc.elv
- I|x: Successfully Installed in /Users/ian/.config/elvish/rc.elv
  more:
    rccode: use os; use runtime; use path; if (os:is-regular (path:dir $runtime:rc-path)/lib/x.elv) { use x; x:init; }     # boot up x-cmd in Elvish.
```

**System (please complete the following information):**
 - Version: 993574f4be7e5b33e00fff858522548
 - Shell: elvish
 - OS: Darwin
 - Arch: arm64
